# Generated by Django 5.2.1 on 2025-05-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_rename_industry_sectors_idea_industry_and_more'),
        ('users', '0002_education_executor_funder_ideator_workexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funder',
            name='ideas_supported',
            field=models.ManyToManyField(blank=True, to='ideas.idea'),
        ),
    ]
