# Generated by Django 5.2.1 on 2025-05-09 12:22

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('elevator_pitch', models.TextField()),
                ('industry_sectors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('description', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, help_text='Max 3 tags', size=3)),
                ('stage', models.CharField(choices=[('brain_spark', '💡 Brain Spark'), ('rough_sketch', '📝 Rough Sketch'), ('proto_play', '🔧 Proto Play'), ('market_snoop', '🕵️ Market Snoop'), ('go_mode', '🚀 Go Mode')], max_length=20)),
                ('commitment', models.CharField(choices=[('side_project', 'Side Project'), ('part_time', 'Part-time'), ('full_time', 'Full-time')], max_length=20)),
                ('funding_status', models.BooleanField(default=False)),
                ('looking_for_funding', models.BooleanField(default=True)),
                ('hiring_status', models.BooleanField(default=False)),
                ('paying_status', models.BooleanField(default=False)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('owners', models.ManyToManyField(related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
