# Generated by Django 5.2.1 on 2025-05-09 12:33

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='industry_sectors',
            new_name='industry',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='commitment',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='owners',
        ),
        migrations.AddField(
            model_name='idea',
            name='users',
            field=models.ManyToManyField(related_name='owned_ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='looking_for_funding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idea',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='idea',
            name='team_size',
            field=models.IntegerField(),
        ),
    ]
